version: "3.8"
services:
  qdrant_primary:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # Qdrantのデフォルトポート
    volumes:
      - qdrant_primary_data:/qdrant/storage
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
      RUST_LOG: "info"
    command: [ "./qdrant", "--uri", "http://qdrant_primary:6335" ]
    cpus: 4.0  # コンテナに割り当てるCPUの数
    mem_limit: 8g  # コンテナに割り当てる最大メモリ量
  # qdrant_secondary:
  #   image: qdrant/qdrant
  #   volumes:
  #     - qdrant_secondary_data:/qdrant/storage
  #   environment:
  #     QDRANT__CLUSTER__ENABLED: "true"
  #     QDRANT__STORAGE__STORAGE_PATH: "/qdrant/storage"
  #     RUST_LOG: "info"
  #   command: [ "./qdrant", "--bootstrap", "http://qdrant_primary:6335" ]
  #   cpus: 2.0  # コンテナに割り当てるCPUの数
  #   mem_limit: 8g  # コンテナに割り当てる最大メモリ量

volumes:
  qdrant_primary_data:
  # qdrant_secondary_data:
